"""Generate reference docs from the code so they cannot drift.

python tools/gen_docs.py            # rewrite docs/CORPUS.md and docs/AUDIT_RULES.md
python tools/gen_docs.py --check    # exit 1 if either file is out of date
"""

from __future__ import annotations

import sys
from pathlib import Path

from sealgrade.audit.rules import RULES
from sealgrade.spec import load_attacks

ROOT = Path(__file__).resolve().parent.parent
TIERS = ("t0", "t1", "t2", "t3")
TIER_NAMES = {"t0": "T0 naive", "t1": "T1 typical", "t2": "T2 compat", "t3": "T3 strict"}


def corpus_doc() -> str:
    attacks = load_attacks(ROOT / "corpus")
    exploits = [a for a in attacks if a.kind == "exploit"]
    probes = [a for a in attacks if a.kind == "probe"]
    lines = [
        "# Exploit corpus",
        "",
        "<!-- Generated by tools/gen_docs.py from corpus/*/attack.toml. Do not edit by hand. -->",
        "",
        f"{len(attacks)} attacks: {len(exploits)} **exploits** (each is a submission that does not "
        f"solve the task; if the verdict says pass, the exploit worked) and {len(probes)} "
        "**boundary probes** (aimed at the strict tier's firewall and output channel; they must be "
        "blocked everywhere).",
        "",
        "The *claimed* outcome per tier is what each attack's manifest asserts. The proof matrix "
        "(see [results](results/matrix.md)) measures it, and CI fails if a claim and a measurement "
        "disagree.",
        "",
        "## Exploits",
        "",
        "| Attack | Classes | " + " | ".join(TIER_NAMES[t] for t in TIERS) + " | What it does |",
        "|---|---|" + "|".join(["---"] * len(TIERS)) + "|---|",
    ]
    for attack in exploits:
        cells = [attack.expected.for_tier(t) or "-" for t in TIERS]
        lines.append(
            f"| `{attack.id}` | {', '.join(attack.classes)} | "
            + " | ".join(cells)
            + f" | {attack.title} |"
        )
    lines += [
        "",
        "## Boundary probes",
        "",
        "| Probe | Classes | What it tries |",
        "|---|---|---|",
    ]
    for attack in probes:
        lines.append(f"| `{attack.id}` | {', '.join(attack.classes)} | {attack.title} |")
    lines += ["", "## Details", ""]
    for attack in attacks:
        lines += [
            f"### `{attack.id}`",
            "",
            f"*{attack.kind}, classes {', '.join(attack.classes)}*",
            "",
            attack.summary.strip(),
            "",
        ]
    return "\n".join(lines) + "\n"


def rules_doc() -> str:
    lines = [
        "# Auditor rules",
        "",
        "<!-- Generated by tools/gen_docs.py from sealgrade.audit.rules. Do not edit by hand. -->",
        "",
        "`sealgrade audit <path>` runs these checks. They are heuristics over text and syntax",
        "trees: specific (each finding names a file and line) and conservative (they prefer a "
        "low-severity note to a confident false alarm), but they can be wrong. SG027 and SG028 "
        "are produced by "
        "running things (`--mutation`, `--dynamic`) rather than by reading text.",
        "",
        "| Rule | Severity | Classes | What it finds | How to fix |",
        "|---|---|---|---|---|",
    ]
    for rule in RULES:
        lines.append(
            f"| `{rule.id}` | {rule.severity.label} | {', '.join(rule.classes)} | "
            f"{rule.title}. {rule.description} | {rule.remedy} |"
        )
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    targets = {
        ROOT / "docs" / "CORPUS.md": corpus_doc(),
        ROOT / "docs" / "AUDIT_RULES.md": rules_doc(),
    }
    stale = []
    for path, content in targets.items():
        if "--check" in argv:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(path.name)
        else:
            path.write_text(content, encoding="utf-8", newline="\n")
            print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        print("out of date:", ", ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
