"""Turn the JSON from ``sealgrade audit tasks --mutation --format json`` into a results page.

sealgrade audit tasks --mutation --format json --out results/mutation.json --fail-on none
python tools/mutation_table.py results/mutation.json docs/results/mutation.md
"""

from __future__ import annotations

import json
import sys
from pathlib import Path


def main(source: Path, target: Path) -> int:
    data = json.loads(source.read_text(encoding="utf-8"))
    rows = []
    totals = {"mutants": 0, "killed": 0, "survived": 0, "invalid": 0}
    survivors: list[tuple[str, str, int, str]] = []
    for task in data["tasks"]:
        m = task.get("mutation")
        if not m:
            continue
        rows.append(
            f"| `{task['task']}` | {m['mutants']} | {m['killed']} | {m['survived']} | "
            f"{m['invalid']} | {m['score'] * 100:.1f}% |"
        )
        for key in totals:
            totals[key] += int(m[key])
        for s in m["survivors"]:
            survivors.append((task["task"], s["operator"], s["line"], s["diff"]))
    valid = totals["killed"] + totals["survived"]
    overall = 100.0 * totals["killed"] / valid if valid else 100.0
    lines = [
        "# Verifier mutation scores",
        "",
        "For each sample task, one plausible bug at a time was planted in the reference solution (operator",
        "and comparison flips, constant tweaks, dropped statements, negated conditions, ...) and graded",
        "against the task's cases. A *killed* mutant fails at least one case; a *survivor* passes them all",
        "(an equivalent program, or a gap in the cases). Mutants that do not compile or do not change the",
        "program are *invalid*. Generated by `tools/mutation_table.py`.",
        "",
        "| Task | Mutants | Killed | Survived | Invalid | Score |",
        "|---|---|---|---|---|---|",
        *rows,
        f"| **All tasks** | {totals['mutants']} | {totals['killed']} | {totals['survived']} | "
        f"{totals['invalid']} | **{overall:.1f}%** |",
        "",
        f"## Survivors ({len(survivors)})",
        "",
        "Each survivor is either behaviourally equivalent to the original or points at a case the task "
        "does not have. They are listed so that a human can decide which.",
        "",
    ]
    for task_id, operator, line, diff in survivors[:40]:
        lines += [f"**`{task_id}`**, {operator} (line {line})", "", "```diff", diff, "```", ""]
    if len(survivors) > 40:
        lines.append(f"... and {len(survivors) - 40} more (see the JSON report).")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {target} ({overall:.1f}% overall, {len(survivors)} survivors)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(Path(sys.argv[1]), Path(sys.argv[2])))
